### ISSUE TITLE
to_pip() is used instead of to_bip()

### ISSUE THREAD

**Issue by BlindState** [U-node/minter-sdk#16]
It looks like the usage of **to_pip** in the string below is the typo. I believe **to_bip** is more suitable here, like it is done in the other **_structure_to_kwargs** methods in the file.
https://github.com/U-node/minter-sdk/blob/e86c6fdba2aeb5babb91f166db1731278df29020/mintersdk/sdk/transactions.py#L1197

**Comment by rymkapro** [comment]
Thanks for your issue.
Version 1.0.33 is already available on PyPI with issue fix.

Please, close the issue, if you are satisfied with the result.

**Comment by BlindState** [comment]
fixed
