### ISSUE TITLE
get_hash() returns wrong transaction hash

### ISSUE THREAD

**Issue by BlindState** [U-node/minter-sdk#17]
Any  minter TX has the length of 64 HEX chars. The functions returns 40.
https://github.com/U-node/minter-sdk/blob/e86c6fdba2aeb5babb91f166db1731278df29020/mintersdk/sdk/transactions.py#L226
https://github.com/U-node/minter-sdk/blob/e86c6fdba2aeb5babb91f166db1731278df29020/mintersdk/sdk/transactions.py#L227

Propose to modify the comment and the code string in the following way: 
        # Return first 64 symbols with prefix
        return MinterHelper.prefix_add(sha.hexdigest()[:64], PREFIX_TX)

**Comment by rymkapro** [comment]
Thanks for your issue.
Version 1.0.33 is already available on PyPI with issue fix.

Please, close the issue, if you are satisfied with the result.

**Comment by BlindState** [comment]
fixed.
