### ISSUE TITLE
What Is it query in "get_transactions"? Can you give me example?

### ISSUE THREAD

**Issue by com-master** [U-node/minter-sdk#2]
What Is it query in "get_transactions"? Can you give me example?

**Comment by U-node** [comment]
Hi, here are some examples:
- `query = "tx.height=1316904"`
- `query = "tx.type='01'"`
or you can make more complex queries:
- `query = "tx.from='ADDRESS_WITHOUT_PREFIX' AND tx.type='01' AND tx.height=1316904"`

**Comment by com-master** [comment]
Big Thanks

чт, 1 авг. 2019 г., 11:54 U-node <notifications@github.com>:
